import 'dart:convert';
import 'dart:io';
import '../models/server.dart';
import 'package:uuid/uuid.dart';

/// Parses and generates OpenSSH config format.
///
/// Standard fields mapped:
///   Host        -> server.name
///   HostName    -> server.host
///   Port        -> server.port
///   User        -> server.username
///   IdentityFile -> server.identityFile
///
/// HostSync extensions stored as structured comments:
///   `#@HostSync-Id` uuid
///   `#@HostSync-AuthType` password|key
///   `#@HostSync-Password` base64
///   `#@HostSync-PrivateKey` base64 (inline key content)
///   `#@HostSync-Passphrase` base64
///   `#@HostSync-Notes` base64
///   `#@HostSync-CreatedAt` iso8601
///   `#@HostSync-UpdatedAt` iso8601
class SshConfigService {
  static const _prefix = '#@HostSync-';

  // ── Parse ───────────────────────────────────────────────────────────

  /// Parses an SSH config string into a list of [Server] objects.
  /// Handles both standard SSH config and HostSync extensions.
  static List<Server> parse(String content) {
    final servers = <Server>[];
    final lines = const LineSplitter().convert(content);

    // Collect blocks: each block starts with "Host ..." and contains
    // the subsequent indented lines + HostSync comment lines.
    final blocks = <_HostBlock>[];
    _HostBlock? current;

    for (final rawLine in lines) {
      final trimmed = rawLine.trim();
      if (trimmed.isEmpty) continue;

      // Check for "Host <name>" line (case-insensitive keyword)
      if (_isHostDirective(trimmed)) {
        current = _HostBlock();
        current.hostAlias = _directiveValue(trimmed);
        blocks.add(current);
        continue;
      }

      if (current == null) continue;

      // HostSync extension comment
      if (trimmed.startsWith(_prefix)) {
        final afterPrefix = trimmed.substring(_prefix.length);
        final spaceIdx = afterPrefix.indexOf(' ');
        if (spaceIdx > 0) {
          final key = afterPrefix.substring(0, spaceIdx);
          final val = afterPrefix.substring(spaceIdx + 1);
          current.extensions[key] = val;
        }
        continue;
      }

      // Standard directive (indented or not)
      if (!trimmed.startsWith('#')) {
        final spaceIdx = _firstWhitespace(trimmed);
        if (spaceIdx > 0) {
          final key = trimmed.substring(0, spaceIdx).toLowerCase();
          final val = trimmed.substring(spaceIdx).trim();
          current.directives[key] = val;
        }
      }
    }

    for (final block in blocks) {
      if (block.hostAlias == null || block.hostAlias == '*') continue;
      servers.add(_blockToServer(block));
    }

    return servers;
  }

  /// Parses an SSH config file from disk.
  static Future<List<Server>> parseFile(String path) async {
    final file = File(path);
    if (!await file.exists()) return [];
    final content = await file.readAsString();
    return parse(content);
  }

  /// Reads the system default SSH config (~/.ssh/config).
  static Future<List<Server>> parseSystemConfig() async {
    final home = Platform.environment['HOME'] ??
        Platform.environment['USERPROFILE'] ??
        '';
    if (home.isEmpty) return [];
    final path = '$home/.ssh/config'
        .replaceAll('\\', '/');
    return parseFile(path);
  }

  // ── Generate ────────────────────────────────────────────────────────

  /// Generates an SSH config string from a list of [Server] objects.
  /// The output is valid OpenSSH config and can be used with `ssh -F`.
  /// HostSync metadata is embedded as structured comments.
  static String generate(List<Server> servers) {
    final buf = StringBuffer();
    buf.writeln('# Generated by HostSync');
    buf.writeln('# This file is compatible with OpenSSH config format.');
    buf.writeln('# HostSync metadata is stored in #@HostSync-* comments.');
    buf.writeln();

    for (var i = 0; i < servers.length; i++) {
      if (i > 0) buf.writeln();
      _writeServer(buf, servers[i]);
    }

    return buf.toString();
  }

  /// Writes servers to an SSH config file on disk.
  static Future<void> writeFile(String path, List<Server> servers) async {
    final file = File(path);
    await file.parent.create(recursive: true);
    await file.writeAsString(generate(servers));
  }

  /// Exports servers and appends/merges into the system SSH config.
  /// Existing non-HostSync Host blocks are preserved.
  static Future<void> mergeIntoSystemConfig(List<Server> servers) async {
    final home = Platform.environment['HOME'] ??
        Platform.environment['USERPROFILE'] ??
        '';
    if (home.isEmpty) return;
    final path = '$home/.ssh/config'.replaceAll('\\', '/');
    final file = File(path);

    String existing = '';
    if (await file.exists()) {
      existing = await file.readAsString();
    }

    // Parse existing to find HostSync-managed blocks
    final managedAliases = <String>{};
    for (final s in servers) {
      managedAliases.add(s.name);
    }

    // Remove old HostSync blocks for these aliases, keep everything else
    final preserved = _removeHostBlocks(existing, managedAliases);

    final buf = StringBuffer();
    if (preserved.trim().isNotEmpty) {
      buf.write(preserved.trimRight());
      buf.writeln();
      buf.writeln();
    }
    buf.write(generate(servers));

    await file.parent.create(recursive: true);
    await file.writeAsString(buf.toString());
  }

  // ── Internal ────────────────────────────────────────────────────────

  static Server _blockToServer(_HostBlock block) {
    final ext = block.extensions;
    final dir = block.directives;

    final id = ext['Id'] ?? const Uuid().v4();
    final name = block.hostAlias ?? 'unknown';
    final host = dir['hostname'] ?? name;
    final port = int.tryParse(dir['port'] ?? '') ?? 22;
    final user = dir['user'] ?? 'root';
    final identityFile = dir['identityfile'];

    // HostSync extensions (base64 encoded)
    final authType = ext['AuthType'] ?? (identityFile != null ? 'key' : 'password');
    final password = _decodeOpt(ext['Password']);
    final privateKey = _decodeOpt(ext['PrivateKey']);
    final passphrase = _decodeOpt(ext['Passphrase']);
    final notes = _decodeOpt(ext['Notes']);

    DateTime? createdAt;
    DateTime? updatedAt;
    try {
      if (ext['CreatedAt'] != null) createdAt = DateTime.parse(ext['CreatedAt']!);
      if (ext['UpdatedAt'] != null) updatedAt = DateTime.parse(ext['UpdatedAt']!);
    } catch (_) {}

    return Server(
      id: id,
      name: name,
      host: host,
      port: port,
      username: user,
      authType: authType,
      identityFile: identityFile,
      password: password,
      privateKey: privateKey,
      passphrase: passphrase,
      notes: notes,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static void _writeServer(StringBuffer buf, Server server) {
    // HostSync metadata as comments (before the Host block for readability)
    buf.writeln('$_prefix${'Id'} ${server.id}');
    buf.writeln('$_prefix${'AuthType'} ${server.authType}');
    if (server.password != null && server.password!.isNotEmpty) {
      buf.writeln('$_prefix${'Password'} ${_encode(server.password!)}');
    }
    if (server.privateKey != null && server.privateKey!.isNotEmpty) {
      buf.writeln('$_prefix${'PrivateKey'} ${_encode(server.privateKey!)}');
    }
    if (server.passphrase != null && server.passphrase!.isNotEmpty) {
      buf.writeln('$_prefix${'Passphrase'} ${_encode(server.passphrase!)}');
    }
    if (server.notes != null && server.notes!.isNotEmpty) {
      buf.writeln('$_prefix${'Notes'} ${_encode(server.notes!)}');
    }
    buf.writeln('$_prefix${'CreatedAt'} ${server.createdAt.toIso8601String()}');
    buf.writeln('$_prefix${'UpdatedAt'} ${server.updatedAt.toIso8601String()}');

    // Standard SSH config block
    buf.writeln('Host ${server.name}');
    buf.writeln('    HostName ${server.host}');
    if (server.port != 22) {
      buf.writeln('    Port ${server.port}');
    }
    buf.writeln('    User ${server.username}');
    if (server.identityFile != null && server.identityFile!.isNotEmpty) {
      buf.writeln('    IdentityFile ${server.identityFile}');
    }
  }

  static bool _isHostDirective(String line) {
    final lower = line.toLowerCase();
    return lower.startsWith('host ') || lower.startsWith('host\t');
  }

  static String _directiveValue(String line) {
    return line.substring(line.indexOf(' ')).trim();
  }

  static int _firstWhitespace(String s) {
    for (var i = 0; i < s.length; i++) {
      if (s[i] == ' ' || s[i] == '\t') return i;
    }
    return -1;
  }

  static String _encode(String value) => base64Encode(utf8.encode(value));

  static String? _decodeOpt(String? encoded) {
    if (encoded == null || encoded.isEmpty) return null;
    try {
      return utf8.decode(base64Decode(encoded));
    } catch (_) {
      return encoded; // fallback: treat as plaintext
    }
  }

  /// Removes Host blocks whose alias is in [aliases] from the config text.
  static String _removeHostBlocks(String config, Set<String> aliases) {
    final lines = const LineSplitter().convert(config);
    final result = <String>[];
    var skipping = false;

    for (final line in lines) {
      final trimmed = line.trim();
      if (_isHostDirective(trimmed)) {
        final alias = _directiveValue(trimmed);
        if (aliases.contains(alias)) {
          skipping = true;
          continue;
        } else {
          skipping = false;
        }
      } else if (skipping) {
        // Skip HostSync extension comments belonging to this block
        if (trimmed.startsWith(_prefix)) continue;
        // Skip indented lines or empty lines within the block
        if (trimmed.isEmpty || line.startsWith(' ') || line.startsWith('\t')) {
          continue;
        }
        // Non-indented, non-Host line means block ended
        skipping = false;
      }

      if (!skipping) {
        result.add(line);
      }
    }

    return result.join('\n');
  }
}

class _HostBlock {
  String? hostAlias;
  final Map<String, String> directives = {};
  final Map<String, String> extensions = {};
}
