use crate::model::{AuthType, Server};
use base64::{engine::general_purpose::STANDARD as B64, Engine};
use uuid::Uuid;

const PREFIX: &str = "#@HostSync-";

/// Parses SSH config text into a list of Servers.
pub fn parse(content: &str) -> Vec<Server> {
    let mut servers = Vec::new();
    let mut current: Option<HostBlock> = None;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }

        if is_host_directive(trimmed) {
            if let Some(block) = current.take() {
                if let Some(s) = block_to_server(block) {
                    servers.push(s);
                }
            }
            let alias = directive_value(trimmed);
            current = Some(HostBlock::new(alias));
            continue;
        }

        let Some(ref mut block) = current else {
            continue;
        };

        if let Some(rest) = trimmed.strip_prefix(PREFIX) {
            if let Some(idx) = rest.find(' ') {
                let key = &rest[..idx];
                let val = &rest[idx + 1..];
                block.extensions.push((key.to_string(), val.to_string()));
            }
            continue;
        }

        if !trimmed.starts_with('#') {
            if let Some(idx) = trimmed.find(|c: char| c.is_whitespace()) {
                let key = trimmed[..idx].to_lowercase();
                let val = trimmed[idx..].trim().to_string();
                block.directives.push((key, val));
            }
        }
    }

    if let Some(block) = current {
        if let Some(s) = block_to_server(block) {
            servers.push(s);
        }
    }

    servers
}

/// Parses the system SSH config file (~/.ssh/config).
pub fn parse_system_config() -> Vec<Server> {
    let home = dirs::home_dir().unwrap_or_default();
    let path = home.join(".ssh").join("config");
    match std::fs::read_to_string(&path) {
        Ok(content) => parse(&content),
        Err(_) => Vec::new(),
    }
}

/// Generates SSH config text from a list of Servers.
pub fn generate(servers: &[Server]) -> String {
    let mut buf = String::from("# Generated by HostSync\n# Compatible with OpenSSH config format.\n\n");
    for (i, server) in servers.iter().enumerate() {
        if i > 0 {
            buf.push('\n');
        }
        write_server(&mut buf, server);
    }
    buf
}

/// Merges HostSync servers into the system SSH config, preserving other entries.
pub fn merge_into_system_config(servers: &[Server]) -> std::io::Result<()> {
    let home = dirs::home_dir().unwrap_or_default();
    let path = home.join(".ssh").join("config");

    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let managed_names: std::collections::HashSet<&str> =
        servers.iter().map(|s| s.name.as_str()).collect();
    let preserved = remove_host_blocks(&existing, &managed_names);

    let mut result = String::new();
    let trimmed = preserved.trim();
    if !trimmed.is_empty() {
        result.push_str(trimmed);
        result.push_str("\n\n");
    }
    result.push_str(&generate(servers));

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, result)
}

fn write_server(buf: &mut String, s: &Server) {
    use std::fmt::Write;
    let _ = writeln!(buf, "{}Id {}", PREFIX, s.id);
    let _ = writeln!(buf, "{}AuthType {}", PREFIX, s.auth_type);
    if let Some(ref pw) = s.password {
        if !pw.is_empty() {
            let _ = writeln!(buf, "{}Password {}", PREFIX, B64.encode(pw.as_bytes()));
        }
    }
    if let Some(ref pk) = s.private_key {
        if !pk.is_empty() {
            let _ = writeln!(buf, "{}PrivateKey {}", PREFIX, B64.encode(pk.as_bytes()));
        }
    }
    if let Some(ref pp) = s.passphrase {
        if !pp.is_empty() {
            let _ = writeln!(buf, "{}Passphrase {}", PREFIX, B64.encode(pp.as_bytes()));
        }
    }
    if let Some(ref n) = s.notes {
        if !n.is_empty() {
            let _ = writeln!(buf, "{}Notes {}", PREFIX, B64.encode(n.as_bytes()));
        }
    }
    let _ = writeln!(buf, "{}CreatedAt {}", PREFIX, s.created_at.to_rfc3339());
    let _ = writeln!(buf, "{}UpdatedAt {}", PREFIX, s.updated_at.to_rfc3339());
    buf.push_str(&s.ssh_config_block());
}

fn is_host_directive(line: &str) -> bool {
    let lower = line.to_lowercase();
    lower.starts_with("host ") || lower.starts_with("host\t")
}

fn directive_value(line: &str) -> String {
    line.split_once(char::is_whitespace)
        .map(|(_, v)| v.trim().to_string())
        .unwrap_or_default()
}

fn decode_opt(encoded: &str) -> Option<String> {
    if encoded.is_empty() {
        return None;
    }
    B64.decode(encoded)
        .ok()
        .and_then(|b| String::from_utf8(b).ok())
        .or_else(|| Some(encoded.to_string()))
}

fn block_to_server(block: HostBlock) -> Option<Server> {
    if block.alias == "*" {
        return None;
    }

    let get_dir = |key: &str| -> Option<String> {
        block
            .directives
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.clone())
    };
    let get_ext = |key: &str| -> Option<String> {
        block
            .extensions
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.clone())
    };

    let id = get_ext("Id").unwrap_or_else(|| Uuid::new_v4().to_string());
    let host = get_dir("hostname").unwrap_or_else(|| block.alias.clone());
    let port = get_dir("port").and_then(|p| p.parse().ok()).unwrap_or(22);
    let user = get_dir("user").unwrap_or_else(|| "root".to_string());
    let identity_file = get_dir("identityfile");

    let auth_type_str = get_ext("AuthType").unwrap_or_default();
    let auth_type = if auth_type_str == "key" || identity_file.is_some() {
        AuthType::Key
    } else {
        AuthType::Password
    };

    let password = get_ext("Password").and_then(|v| decode_opt(&v));
    let private_key = get_ext("PrivateKey").and_then(|v| decode_opt(&v));
    let passphrase = get_ext("Passphrase").and_then(|v| decode_opt(&v));
    let notes = get_ext("Notes").and_then(|v| decode_opt(&v));

    let created_at = get_ext("CreatedAt")
        .and_then(|v| chrono::DateTime::parse_from_rfc3339(&v).ok())
        .map(|d| d.with_timezone(&chrono::Utc))
        .unwrap_or_else(chrono::Utc::now);
    let updated_at = get_ext("UpdatedAt")
        .and_then(|v| chrono::DateTime::parse_from_rfc3339(&v).ok())
        .map(|d| d.with_timezone(&chrono::Utc))
        .unwrap_or_else(chrono::Utc::now);

    Some(Server {
        id,
        name: block.alias,
        host,
        port,
        username: user,
        auth_type,
        identity_file,
        password,
        private_key,
        passphrase,
        notes,
        created_at,
        updated_at,
    })
}

fn remove_host_blocks(config: &str, aliases: &std::collections::HashSet<&str>) -> String {
    let mut result = Vec::new();
    let mut skipping = false;

    for line in config.lines() {
        let trimmed = line.trim();
        if is_host_directive(trimmed) {
            let alias = directive_value(trimmed);
            if aliases.contains(alias.as_str()) {
                skipping = true;
                continue;
            } else {
                skipping = false;
            }
        } else if skipping {
            if trimmed.starts_with(PREFIX) || trimmed.is_empty()
                || line.starts_with(' ') || line.starts_with('\t')
            {
                continue;
            }
            skipping = false;
        }
        if !skipping {
            result.push(line);
        }
    }
    result.join("\n")
}

struct HostBlock {
    alias: String,
    directives: Vec<(String, String)>,
    extensions: Vec<(String, String)>,
}

impl HostBlock {
    fn new(alias: String) -> Self {
        Self {
            alias,
            directives: Vec::new(),
            extensions: Vec::new(),
        }
    }
}
